


anti-macro:
  enabled: true

disable:
  hopper: true
  enchanment-table: true
  restone: true
  anvil: true
  slime-split: false

combatlog:
  enabled: false
  combat-seconds: 30
  commands-permitted:
    - /report