name: EduEssentials
description: Sistemas essenciais de qualquer servidor
main: net.eduard.essentials.EduEssentials
version: ${project.version}
author: Eduard
authors: [Eduard]
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD
