
no-slime-split: false
chat-delayed: true
chat-delay-seconds: 1
command-delayed: true
command-delay-seconds: 2
hopper-blocked: true
enchament-table-blocked: true
restone-blocked: true
anvil-blocked: true
reduce-drop-lag: true
anti-macro-enabled: true
auto-pickup-enabled: true
combatlog:
  enabled: false
  combat-seconds: 30
  commands-permitted:
  - /report
  
blocked-commands:
- /plugins
blocked-tab-commands:
- /plugins

commands: